# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: ec2-54-163-249-150.compute-1.amazonaws.com
  port: 5432
  database: dcbq83b8cjheb6
  user: vpdqnxnshrguat
  password: A7hnURCwoNQT1_tsHAcyxymlkW

development:
  adapter: postgresql
  host: ec2-54-163-249-150.compute-1.amazonaws.com
  port: 5432
  database: dcbq83b8cjheb6
  user: vpdqnxnshrguat
  password: A7hnURCwoNQT1_tsHAcyxymlkW

test:
  adapter: postgresql
  host: ec2-54-163-249-150.compute-1.amazonaws.com
  port: 5432
  database: dcbq83b8cjheb6
  user: vpdqnxnshrguat
  password: A7hnURCwoNQT1_tsHAcyxymlkW

production:
  adapter: postgresql
  host: ec2-54-163-249-150.compute-1.amazonaws.com
  port: 5432
  database: dcbq83b8cjheb6
  user: vpdqnxnshrguat
  password: A7hnURCwoNQT1_tsHAcyxymlkW
